/*
 *
 * CreateBill constants
 *
 */

export const DEFAULT_ACTION = 'app/CreateBill/DEFAULT_ACTION';

export const CHECK_COUSTOMER_AMOUNT_REQUEST = 'app/CreateBill/CHECK_COUSTOMER_AMOUNT_REQUEST';
export const CHECK_COUSTOMER_AMOUNT_SUCCESS = 'app/CreateBill/CHECK_COUSTOMER_AMOUNT_SUCCESS';
export const CHECK_COUSTOMER_AMOUNT_FAILURE = 'app/CreateBill/CHECK_COUSTOMER_AMOUNT_FAILURE';

export const CHOOSE_SEATS_REQUEST = 'app/CreateBill/CHOOSE_SEATS_REQUEST';
export const CHOOSE_SEATS_SUCCESS = 'app/CreateBill/CHOOSE_SEATS_SUCCESS';
export const CHOOSE_SEATS_FAILURE = 'app/CreateBill/CHOOSE_SEATS_FAILURE';

export const CREATE_BILL_REQUEST = 'app/CreateBill/CREATE_BILL_REQUEST';
export const CREATE_BILL_SUCCESS = 'app/CreateBill/CREATE_BILL_SUCCESS';
export const CREATE_BILL_FAILURE = 'app/CreateBill/CREATE_BILL_FAILURE';
